name: Java CI

on:
  push:
    branches: [ main ]
    paths:
      - '04_data-science/HR_Analytics/**'
      - '.github/workflows/java-ci.yml'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: |
        cd 04_data-science/HR_Analytics
        mvn -B package --file pom.xml
    
    - name: Run tests
      run: |
        cd 04_data-science/HR_Analytics
        mvn test
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: 04_data-science/HR_Analytics/target/site/jacoco/jacoco.xml
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}

  docker:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./04_data-science/HR_Analytics
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/hr-analytics:latest 